apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
  labels:
    name: webapp
spec:
  containers:
  - name: hellocontain
    image: gcr.io/google-samples/hello-app:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
